@echo off
echo Iniciando Noticias TendenciaRD...
echo Instalando dependencias (esto solo tomara un momento la primera vez)...
call npm install
echo Abriendo el panel en el navegador...
start http://localhost:3000
echo Iniciando servidor local...
npm run dev
pause
